// Code generated by MockGen. DO NOT EDIT.
// Source: health.go
//
// Generated by this command:
//
//	mockgen -source=health.go -destination=mock/health.go
//

// Package mock_handler is a generated GoMock package.
package mock_handler

import (
	reflect "reflect"

	gin "github.com/gin-gonic/gin"
	gomock "go.uber.org/mock/gomock"
)

// MockIHealthCheckHandler is a mock of IHealthCheckHandler interface.
type MockIHealthCheckHandler struct {
	ctrl     *gomock.Controller
	recorder *MockIHealthCheckHandlerMockRecorder
	isgomock struct{}
}

// MockIHealthCheckHandlerMockRecorder is the mock recorder for MockIHealthCheckHandler.
type MockIHealthCheckHandlerMockRecorder struct {
	mock *MockIHealthCheckHandler
}

// NewMockIHealthCheckHandler creates a new mock instance.
func NewMockIHealthCheckHandler(ctrl *gomock.Controller) *MockIHealthCheckHandler {
	mock := &MockIHealthCheckHandler{ctrl: ctrl}
	mock.recorder = &MockIHealthCheckHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIHealthCheckHandler) EXPECT() *MockIHealthCheckHandlerMockRecorder {
	return m.recorder
}

// Check mocks base method.
func (m *MockIHealthCheckHandler) Check(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Check", c)
}

// Check indicates an expected call of Check.
func (mr *MockIHealthCheckHandlerMockRecorder) Check(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Check", reflect.TypeOf((*MockIHealthCheckHandler)(nil).Check), c)
}
