// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go
//
// Generated by this command:
//
//	mockgen -source=repository.go -destination=mock/repository.go
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIDBRepository is a mock of IDBRepository interface.
type MockIDBRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIDBRepositoryMockRecorder
	isgomock struct{}
}

// MockIDBRepositoryMockRecorder is the mock recorder for MockIDBRepository.
type MockIDBRepositoryMockRecorder struct {
	mock *MockIDBRepository
}

// NewMockIDBRepository creates a new mock instance.
func NewMockIDBRepository(ctrl *gomock.Controller) *MockIDBRepository {
	mock := &MockIDBRepository{ctrl: ctrl}
	mock.recorder = &MockIDBRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIDBRepository) EXPECT() *MockIDBRepositoryMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockIDBRepository) Get(key string) (*string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", key)
	ret0, _ := ret[0].(*string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockIDBRepositoryMockRecorder) Get(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockIDBRepository)(nil).Get), key)
}

// Set mocks base method.
func (m *MockIDBRepository) Set(key, value string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", key, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockIDBRepositoryMockRecorder) Set(key, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockIDBRepository)(nil).Set), key, value)
}
