basePath: /api/v1
definitions:
  handler.response:
    type: object
host: localhost:8080
info:
  contact:
    email: shotarowatanabe6@gmail.com
    name: shotarowatanabe6
  description: This is a blog server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Blog API
  version: "1.0"
paths:
  /health:
    get:
      description: ヘルスチェック
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.response'
      summary: Check health status
swagger: "2.0"
